name: Semgrep

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]
  schedule:
    - cron: "37 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run Semgrep
        run: semgrep scan --error --config p/default --config p/security-audit --config p/secrets .
